<?php
/* Sandy Feeds Module */

function sandyfeeds_help($path, $arg)
{
	switch($path){
		case "admin/help#sandyfeeds":
	      return '<p>' . t("Info on Sandy Feeds") . '</p>';
	      break;
	}
}

function sandyfeeds_block_info() {
  $blocks['sandyfeeds'] = array(
    'info' => t('Sandy Feeds'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}
